-- 增量脚本
-- 2017.10.13 start
use nbo_dev;

ALTER TABLE NBO_K8S_RUNTIME_ENV ADD ENV_TYPE VARCHAR(30);
ALTER TABLE NBO_K8S_RUNTIME_ENV ADD DCOS_TOKEN VARCHAR(30);

CREATE TABLE DCOS_NBO_PROJECT
(
    ID BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    RUNTIME_ENV_ID BIGINT(20) COMMENT 'DCOS运行环境ID',
    NBO_PROJECT_ID BIGINT(20) COMMENT 'NBO项目ID',
    DCOS_PROJECT_ID VARCHAR(32) COMMENT 'DCOS项目ID',
    INSERT_TIME DATETIME,
    INSERT_OPERATOR VARCHAR(50),
    INSERT_OPERATOR_ID BIGINT(20),
    MODIFY_TIME DATETIME,
    MODIFY_OPERATOR VARCHAR(50),
    MODIFY_OPERATOR_ID BIGINT(20)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DCOS与项目关联表';


CREATE TABLE DCOS_NBO_ENV
(
    ID BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    PROJECT_ID BIGINT(20) COMMENT '项目ID',
    PROJECT_ENV_ID BIGINT(20) COMMENT 'NBO项目ID',
    DCOS_CLUSTER_ID VARCHAR(32) COMMENT 'DCOS集群ID',
    DCOS_NBO_PROJECT_ID BIGINT(20) COMMENT 'DCOS与项目关联表ID',
    INSERT_TIME DATETIME,
    INSERT_OPERATOR VARCHAR(50),
    INSERT_OPERATOR_ID BIGINT(20),
    MODIFY_TIME DATETIME,
    MODIFY_OPERATOR VARCHAR(50),
    MODIFY_OPERATOR_ID BIGINT(20)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DCOS项目环境表';



CREATE TABLE DCOS_NBO_HOST
(
    ID BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    HOST_IP VARCHAR(50)  COMMENT '主机IP',
    HOST_NAME VARCHAR(50)  COMMENT '主机名称',
    HOST_USER_NAME VARCHAR(50) COMMENT 'ssh用户名',
    HOST_PASSWORD VARCHAR(50) COMMENT 'ssh密码',
    HOST_PORT INT(5) COMMENT 'ssh端口',
    HOST_ROOT_PASSWORD VARCHAR(50) COMMENT 'root密码',
    DCOS_HOST_ID VARCHAR(32) COMMENT 'DCOS主机ID',
    DCOS_NBO_PROJECT_ID BIGINT(20) COMMENT 'DCOS与项目关联表ID',
    PROJECT_ID BIGINT(20) COMMENT '项目ID',
    INSERT_TIME DATETIME,
    INSERT_OPERATOR VARCHAR(50),
    INSERT_OPERATOR_ID BIGINT(20),
    MODIFY_TIME DATETIME,
    MODIFY_OPERATOR VARCHAR(50),
    MODIFY_OPERATOR_ID BIGINT(20)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DCOS项目主机表';


 CREATE TABLE DCOS_NBO_ENV_HOST
(
    ID BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DCOS_NBO_ENV_ID BIGINT(20) COMMENT 'DCOS环境ID',
    DCOS_NBO_HOST_ID BIGINT(20) COMMENT 'DCOS主机ID',
    INSERT_TIME DATETIME,
    INSERT_OPERATOR VARCHAR(50),
    INSERT_OPERATOR_ID BIGINT(20),
    MODIFY_TIME DATETIME,
    MODIFY_OPERATOR VARCHAR(50),
    MODIFY_OPERATOR_ID BIGINT(20)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DCOS环境与主机关联表';

 CREATE TABLE DCOS_IMAGE
(
    ID BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IMAGE_NAME VARCHAR(100) COMMENT '镜像名称',
    RUNTIME_ENV_ID BIGINT(20) COMMENT '运行环境ID',
    INSERT_TIME DATETIME,
    INSERT_OPERATOR VARCHAR(50),
    INSERT_OPERATOR_ID BIGINT(20),
    MODIFY_TIME DATETIME,
    MODIFY_OPERATOR VARCHAR(50),
    MODIFY_OPERATOR_ID BIGINT(20)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DCOS镜像表';

CREATE TABLE NBO_APP_ENV_ROLE (
  	ID BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	INSERT_OPERATOR VARCHAR(50),
	INSERT_OPERATOR_ID BIGINT(20),
	INSERT_TIME DATE,
	MODIFY_OPERATOR VARCHAR(50),
	MODIFY_OPERATOR_ID BIGINT(20),
	MODIFY_TIME DATE,
  	PROJECT_ID BIGINT(20),
  	APP_ID BIGINT(20),
  	ENV_ID BIGINT(20)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='应用环境角色关系表';

ALTER TABLE NBO_DEPLOY_VERSION ADD DCOS_APP_ID VARCHAR(32) COMMENT 'DCOS应用ID';
ALTER TABLE NBO_DEPLOY_VERSION ADD DCOS_IMAGE_NAME VARCHAR(100) COMMENT 'DCOS镜像名称';
ALTER TABLE NBO_DEPLOY_VERSION ADD DCOS_PORT VARCHAR(200) COMMENT 'DCOS端口号';
ALTER TABLE nbo_deploy_version ADD COLUMN APP_DEPLOY_NAME VARCHAR(100) NULL COMMENT '应用在中间件中部署时显示的名称';


UPDATE  NBO_K8S_RUNTIME_ENV a SET a.ENV_TYPE='K8S' WHERE a.KEY_DATA IS NOT NULL;
UPDATE  NBO_K8S_RUNTIME_ENV a SET a.ENV_TYPE='DCOS' WHERE a.KEY_DATA IS NULL;

update NBO_BUILD_TASK_TEMP b set b.build_command = 'mvn clean install -Dmaven.test.skip=true' where b.support_code_type='java' and  b.action_type='package' and b.build_tools='maven';

UPDATE NBO_K8S_RUNTIME_ENV SET APP_INNER_ACCESS_IP='127.0.0.1', APP_PUBLIC_ACCESS_IP='183.66.65.223', K8S_URL='https://183.66.65.223:26443', REGISTRY_URL='192.168.0.8:5000', CERT_DATA='LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQzVENDQXNXZ0F3SUJBZ0lVTVJWNmdRWGFaVFI0VTFPWXJKR0hwZ2xUbXRJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEUzTURjd016QTJOVE13TUZvWERURTRNRGN3TXpBMk5UTXdNRm93YXpFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RnpBVgpCZ05WQkFvVERuTjVjM1JsYlRwdFlYTjBaWEp6TVE4d0RRWURWUVFMRXdaVGVYTjBaVzB4RGpBTUJnTlZCQU1UCkJXRmtiV2x1TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFtdy9YWUtUWnhvS1gKN2FvazUrdXMwbnVTWmN1d2FDTjhpVk0rOXN5bHFxTmU4SjZleUFFbFQ1SGFaZlovUGIyWDkwc2RKbXNXM2pORQo3NnYvOE5TSVVOUW9od0RoUStlaVdPbGE2L20zNjIvdWZLeUdUNmdFSFJ3TE0rdkcvK1p3eG5IV1pzVVUzWUdsCnFnZHhWcDdHNWliRW4wNnlxSDFnbU5iak1TTWM0V1BWdzdSVFVqRWkvWlNib3E1cjFDalJIWWhtWTZrWnBERWYKSm10c0F4WUhubVRCUmFWUGJxMjMwOXk5Z3lZRUdvTEhVemVUdU1ZVm0rbDJyLzlnNzk3MWxlOFkvR3Q3d0U3Uwp4bFRtREZnQlVBYTNwS3R4bTZad3c3RVlmQWduZm1PeVh0T1VWK0pXVitjZkdnQXlic08yb2lMWW53OXBaVnNkCkl2OG1qZEJ4NVFJREFRQUJvMzh3ZlRBT0JnTlZIUThCQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3RkFZSUt3WUIKQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRUZBc1VXSXA1T3dsNwpaQ21JQnpoTEJNS2xaVmRjTUI4R0ExVWRJd1FZTUJhQUZGOXA1V1JycUhNdzhNbkpodGIzaFBFaUNSMVFNQTBHCkNTcUdTSWIzRFFFQkN3VUFBNElCQVFDSFRvS1BIbk02Sm9TOUZJUGV0UHlRY2g0ck1wUFBZU051NDJMdmtYRTgKenBPZDVWUVBlYmliazJvYnIzVGp2RHlBczZ6L3FWbzFGWmJqUnBvbCt0VWhLVjFKMEY5MVRNUnF1N2Zva1RBLwpvSXZhOUUrTlVtTXRvYzVRNXV1a3RndmV6dURhckZONHY1cGZ2Y2xYcHVJWHorSVJRNzBIVzN6WEp4RVVybnYyCk04U2U2dW1QeEFSL3B6S2VUOUdLTzJOdkNmU0EweTZtOEJWZTg1b0RpanMydGdSK2crenVIaXlzazhtV2pLUXUKODBrbzlSQkd5endHZzRYQk4yUUFjeURWY1BXQjB3d1E5Qit1TFRDRFJuWVJEQkpUWnNLRjZvTHlQOG5xSEowOAo2VVhuK2Z1eVJaZmJkUU42SllEdXFRZFpvenp3eTJISWFRZ1ZUNkxuWkVRLwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==', KEY_DATA='LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcGdJQkFBS0NBUUVBbXcvWFlLVFp4b0tYN2FvazUrdXMwbnVTWmN1d2FDTjhpVk0rOXN5bHFxTmU4SjZlCnlBRWxUNUhhWmZaL1BiMlg5MHNkSm1zVzNqTkU3NnYvOE5TSVVOUW9od0RoUStlaVdPbGE2L20zNjIvdWZLeUcKVDZnRUhSd0xNK3ZHLytad3huSFdac1VVM1lHbHFnZHhWcDdHNWliRW4wNnlxSDFnbU5iak1TTWM0V1BWdzdSVApVakVpL1pTYm9xNXIxQ2pSSFlobVk2a1pwREVmSm10c0F4WUhubVRCUmFWUGJxMjMwOXk5Z3lZRUdvTEhVemVUCnVNWVZtK2wyci85Zzc5NzFsZThZL0d0N3dFN1N4bFRtREZnQlVBYTNwS3R4bTZad3c3RVlmQWduZm1PeVh0T1UKVitKV1YrY2ZHZ0F5YnNPMm9pTFludzlwWlZzZEl2OG1qZEJ4NVFJREFRQUJBb0lCQVFDRGZUMXdNSnFUWVM2ZwpWUVdTdlNFQ0k5T1RDdFQrbWdrREVscDBRam5CcDJQY3UwVjk2S3JRL0tlc2l3aC9QSVRmS1EwQkJSS1JQZnlaCkdNdWlWemQ1QTArU204WnFKTVJnalJHU3hXR1cvb1hIcHkwRjR6NEp5VHdldlRNMDBSNlV5UGU4a2ljTlp1RXEKZThFNmFNM1ZZTTZmSU1jVFphNUNMUWJmSmgxWmFsTnp1MGNVMWNBZTZES205WUdyblI2VFFRV3EyR2htS0JVNgpvN1FPVVpyMTN6ZVkzZGJseGw5WTY5NUNSNWlyVHNTRlI0QmRKVS9YbkRwby9MY0pMczd6YW9lV0N5dXNmSnN5CnMwazk2dmdyaFlvNmdxV3VoQVc2NUszaExocUM4VlZPYVJJL2x5THVmdGk4ZjZTSXUyWUVYbnljbDhwVDdYTlgKZ0IwS010YUJBb0dCQU1ZSG5ZWVBBbzNzZnc0TlMrc2p0ZVhhcVBBc1FLM1dGdTAvSXc2b1FpbUk0UUw4Y1FaeQphOWRjcGtIS0VCWjZkMko1Ly9XMEdBSEVUTTJmZlJtU0lLeHRnTC9oUCtzTWUzU051VG5WK3NSdktZRzJhN29PCnFCQ0U2SmRzM3lNNnhSejI2WUZIcHhLNVJ6UldsMGtLWUxjSSs1K3pSSEFjSVRPV0dRWS9PVXN4QW9HQkFNaDAKTk5LeWttRzE5U0FqUHJMRUFSeFQzMlNlemV4dS9ySjNlclhPNG5SMXg2TExUWUxmUDhmQ2c0anZCTlYyOVJjWApUL2Y5SjQ0SGUya3F5Y29kNFVIcVlBUnZ3b244MzYvc3VBZklrRHNrNG5RNEdJWTF5UXFHR1VVN0pKUFRGK09uCkVUeFRPeGlOQXJPbE11YVNQV1dmbVpaWU14OHdlelV4aHdsMUhEejFBb0dCQUlJUkhHaWgwVGF3Zjk4VjRxaGwKd3lKZWxSbHlwMlRHT2piSGdsb3RMNCtpUk5BMlNISklrd1pYNXlkTTlYWWVKKzI1WGVIZTBPblFLZlhnYkVWdwpVaCtPcU1MZXlxR3lpQi9NdWp6L2kzNmIyTEpHdzhqbnVZRm9HbkRpNUVoNllGOGUyYzI4NTBLSUNQbWFhakZpCkxKWHJ3NEZvT0dvK1A1eG5XTFplcmwzeEFvR0JBSU1rWTVxazhWZXpyMWNETi9YRWZlV0dpZFJPZ1BKNSsyL08KOHgwVzZOakFaWWQvOG9uNGZNVzM0RTRwOGNPbU85cUxpZW40V1hSMk9Lc3BMek5vTVFMcXp6Nlh6M0p2V2ZqQwpxZk9OcDY3S0JzMTZGYkZZWnRyWHVKaXVoTk9oZXpPWkRaR2w4amV4cVY3V2FXS25zanRXR3lsZE1yVHBCdkphCklMcHpQN0l4QW9HQkFMWEdyZUpEcnVxWi8weUhlNVNzSXY5L0Rqd1JrRTdrYWdBN2VNLzYwWHlodkl5V2Z5Z20KNjFwb0ozK3V3M3FNS09IeGJMenZzVE9KWnUvZFBVUzdMeWZlU1p4UDAvdkNJaC82Ny9pQzQ2Tlpwa0xHWnJnZgpnOWpuK2JNOFFoZ2Z3ODhBcEtHcnhzOXBUZ1ZmY3ROaE5laU9STjRnNSsycEU2K25Jd25XRzJWQQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=' WHERE ID='22';

UPDATE NBO_PARAMETERS SET VALUE_='https://183.66.65.223:26443' WHERE ID='1';
UPDATE NBO_PARAMETERS SET VALUE_='192.168.0.8:5000' WHERE ID='2';
UPDATE NBO_PARAMETERS SET VALUE_='192.168.0.8:5000/newtouchone/v4-build-java:v4-3.4' WHERE ID='3';
UPDATE NBO_PARAMETERS SET VALUE_='192.168.0.8:5000/newtouchone/v4-build-android:4.1.0' WHERE ID='4';
UPDATE NBO_PARAMETERS SET VALUE_='10.182.88.213:5000/newtouchone/v4-build-ios:test-4.1.0' WHERE ID='5';
UPDATE NBO_PARAMETERS SET VALUE_='192.168.0.8:5000/newtouchone/v4-build-php:v4.1.12' WHERE ID='6';
UPDATE NBO_PARAMETERS SET VALUE_='registry.one2.newtouch.com:5000/mohaijiang/ansible-deploy:4.2.5-rc1' WHERE ID='7';
UPDATE NBO_PARAMETERS SET VALUE_='183.66.65.223:7480' WHERE ID='8';
UPDATE NBO_PARAMETERS SET VALUE_='183.66.65.223:7480' WHERE ID='9';
UPDATE NBO_PARAMETERS SET VALUE_='3AU4D7VTLKNZDXERST6I' WHERE ID='10';
UPDATE NBO_PARAMETERS SET VALUE_='4dvYmu1pON8vsPvBFmfRTBGd8PfCxlXENZDnNIYk' WHERE ID='11';
UPDATE NBO_PARAMETERS SET VALUE_='http://sonar.one1.newtouch.com' WHERE ID='13';
UPDATE NBO_PARAMETERS SET VALUE_='http://sonar.one1.newtouch.com' WHERE ID='14';
UPDATE NBO_PARAMETERS SET VALUE_='http://183.66.65.223:10080' WHERE ID='169';
UPDATE NBO_PARAMETERS SET VALUE_='http://183.66.65.223:10080' WHERE ID='170';
UPDATE NBO_PARAMETERS SET VALUE_='yB5MpLKVnv41tivrgmwe' WHERE ID='171';
UPDATE NBO_PARAMETERS SET VALUE_='LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQzVENDQXNXZ0F3SUJBZ0lVTVJWNmdRWGFaVFI0VTFPWXJKR0hwZ2xUbXRJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEUzTURjd016QTJOVE13TUZvWERURTRNRGN3TXpBMk5UTXdNRm93YXpFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RnpBVgpCZ05WQkFvVERuTjVjM1JsYlRwdFlYTjBaWEp6TVE4d0RRWURWUVFMRXdaVGVYTjBaVzB4RGpBTUJnTlZCQU1UCkJXRmtiV2x1TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFtdy9YWUtUWnhvS1gKN2FvazUrdXMwbnVTWmN1d2FDTjhpVk0rOXN5bHFxTmU4SjZleUFFbFQ1SGFaZlovUGIyWDkwc2RKbXNXM2pORQo3NnYvOE5TSVVOUW9od0RoUStlaVdPbGE2L20zNjIvdWZLeUdUNmdFSFJ3TE0rdkcvK1p3eG5IV1pzVVUzWUdsCnFnZHhWcDdHNWliRW4wNnlxSDFnbU5iak1TTWM0V1BWdzdSVFVqRWkvWlNib3E1cjFDalJIWWhtWTZrWnBERWYKSm10c0F4WUhubVRCUmFWUGJxMjMwOXk5Z3lZRUdvTEhVemVUdU1ZVm0rbDJyLzlnNzk3MWxlOFkvR3Q3d0U3Uwp4bFRtREZnQlVBYTNwS3R4bTZad3c3RVlmQWduZm1PeVh0T1VWK0pXVitjZkdnQXlic08yb2lMWW53OXBaVnNkCkl2OG1qZEJ4NVFJREFRQUJvMzh3ZlRBT0JnTlZIUThCQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3RkFZSUt3WUIKQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRUZBc1VXSXA1T3dsNwpaQ21JQnpoTEJNS2xaVmRjTUI4R0ExVWRJd1FZTUJhQUZGOXA1V1JycUhNdzhNbkpodGIzaFBFaUNSMVFNQTBHCkNTcUdTSWIzRFFFQkN3VUFBNElCQVFDSFRvS1BIbk02Sm9TOUZJUGV0UHlRY2g0ck1wUFBZU051NDJMdmtYRTgKenBPZDVWUVBlYmliazJvYnIzVGp2RHlBczZ6L3FWbzFGWmJqUnBvbCt0VWhLVjFKMEY5MVRNUnF1N2Zva1RBLwpvSXZhOUUrTlVtTXRvYzVRNXV1a3RndmV6dURhckZONHY1cGZ2Y2xYcHVJWHorSVJRNzBIVzN6WEp4RVVybnYyCk04U2U2dW1QeEFSL3B6S2VUOUdLTzJOdkNmU0EweTZtOEJWZTg1b0RpanMydGdSK2crenVIaXlzazhtV2pLUXUKODBrbzlSQkd5endHZzRYQk4yUUFjeURWY1BXQjB3d1E5Qit1TFRDRFJuWVJEQkpUWnNLRjZvTHlQOG5xSEowOAo2VVhuK2Z1eVJaZmJkUU42SllEdXFRZFpvenp3eTJISWFRZ1ZUNkxuWkVRLwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==' WHERE ID='160';
UPDATE NBO_PARAMETERS SET VALUE_='LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcGdJQkFBS0NBUUVBbXcvWFlLVFp4b0tYN2FvazUrdXMwbnVTWmN1d2FDTjhpVk0rOXN5bHFxTmU4SjZlCnlBRWxUNUhhWmZaL1BiMlg5MHNkSm1zVzNqTkU3NnYvOE5TSVVOUW9od0RoUStlaVdPbGE2L20zNjIvdWZLeUcKVDZnRUhSd0xNK3ZHLytad3huSFdac1VVM1lHbHFnZHhWcDdHNWliRW4wNnlxSDFnbU5iak1TTWM0V1BWdzdSVApVakVpL1pTYm9xNXIxQ2pSSFlobVk2a1pwREVmSm10c0F4WUhubVRCUmFWUGJxMjMwOXk5Z3lZRUdvTEhVemVUCnVNWVZtK2wyci85Zzc5NzFsZThZL0d0N3dFN1N4bFRtREZnQlVBYTNwS3R4bTZad3c3RVlmQWduZm1PeVh0T1UKVitKV1YrY2ZHZ0F5YnNPMm9pTFludzlwWlZzZEl2OG1qZEJ4NVFJREFRQUJBb0lCQVFDRGZUMXdNSnFUWVM2ZwpWUVdTdlNFQ0k5T1RDdFQrbWdrREVscDBRam5CcDJQY3UwVjk2S3JRL0tlc2l3aC9QSVRmS1EwQkJSS1JQZnlaCkdNdWlWemQ1QTArU204WnFKTVJnalJHU3hXR1cvb1hIcHkwRjR6NEp5VHdldlRNMDBSNlV5UGU4a2ljTlp1RXEKZThFNmFNM1ZZTTZmSU1jVFphNUNMUWJmSmgxWmFsTnp1MGNVMWNBZTZES205WUdyblI2VFFRV3EyR2htS0JVNgpvN1FPVVpyMTN6ZVkzZGJseGw5WTY5NUNSNWlyVHNTRlI0QmRKVS9YbkRwby9MY0pMczd6YW9lV0N5dXNmSnN5CnMwazk2dmdyaFlvNmdxV3VoQVc2NUszaExocUM4VlZPYVJJL2x5THVmdGk4ZjZTSXUyWUVYbnljbDhwVDdYTlgKZ0IwS010YUJBb0dCQU1ZSG5ZWVBBbzNzZnc0TlMrc2p0ZVhhcVBBc1FLM1dGdTAvSXc2b1FpbUk0UUw4Y1FaeQphOWRjcGtIS0VCWjZkMko1Ly9XMEdBSEVUTTJmZlJtU0lLeHRnTC9oUCtzTWUzU051VG5WK3NSdktZRzJhN29PCnFCQ0U2SmRzM3lNNnhSejI2WUZIcHhLNVJ6UldsMGtLWUxjSSs1K3pSSEFjSVRPV0dRWS9PVXN4QW9HQkFNaDAKTk5LeWttRzE5U0FqUHJMRUFSeFQzMlNlemV4dS9ySjNlclhPNG5SMXg2TExUWUxmUDhmQ2c0anZCTlYyOVJjWApUL2Y5SjQ0SGUya3F5Y29kNFVIcVlBUnZ3b244MzYvc3VBZklrRHNrNG5RNEdJWTF5UXFHR1VVN0pKUFRGK09uCkVUeFRPeGlOQXJPbE11YVNQV1dmbVpaWU14OHdlelV4aHdsMUhEejFBb0dCQUlJUkhHaWgwVGF3Zjk4VjRxaGwKd3lKZWxSbHlwMlRHT2piSGdsb3RMNCtpUk5BMlNISklrd1pYNXlkTTlYWWVKKzI1WGVIZTBPblFLZlhnYkVWdwpVaCtPcU1MZXlxR3lpQi9NdWp6L2kzNmIyTEpHdzhqbnVZRm9HbkRpNUVoNllGOGUyYzI4NTBLSUNQbWFhakZpCkxKWHJ3NEZvT0dvK1A1eG5XTFplcmwzeEFvR0JBSU1rWTVxazhWZXpyMWNETi9YRWZlV0dpZFJPZ1BKNSsyL08KOHgwVzZOakFaWWQvOG9uNGZNVzM0RTRwOGNPbU85cUxpZW40V1hSMk9Lc3BMek5vTVFMcXp6Nlh6M0p2V2ZqQwpxZk9OcDY3S0JzMTZGYkZZWnRyWHVKaXVoTk9oZXpPWkRaR2w4amV4cVY3V2FXS25zanRXR3lsZE1yVHBCdkphCklMcHpQN0l4QW9HQkFMWEdyZUpEcnVxWi8weUhlNVNzSXY5L0Rqd1JrRTdrYWdBN2VNLzYwWHlodkl5V2Z5Z20KNjFwb0ozK3V3M3FNS09IeGJMenZzVE9KWnUvZFBVUzdMeWZlU1p4UDAvdkNJaC82Ny9pQzQ2Tlpwa0xHWnJnZgpnOWpuK2JNOFFoZ2Z3ODhBcEtHcnhzOXBUZ1ZmY3ROaE5laU9STjRnNSsycEU2K25Jd25XRzJWQQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=' WHERE ID='161';
UPDATE NBO_PARAMETERS SET VALUE_='192.168.0.8:5000/newtouchone/v4-build-static-resource:0.15' WHERE ID='162';
UPDATE NBO_PARAMETERS SET VALUE_='busybox' WHERE ID='181';

-- 2017.10.13 end


-- 2017.10.26 start

CREATE TABLE NBO_HOST_NODE_ENV (
ID BIGINT(20) NOT NULL ,
NBO_ENV_HOST_ID BIGINT(20) NULL COMMENT '主机环境集群master环境' ,
NODE_NAME VARCHAR(50) NULL,
NODE_IP VARCHAR(50) NULL,
NODE_PORT VARCHAR(50) NULL,
NODE_USER_NAME VARCHAR(50) NULL,
NODE_PASSOWRD VARCHAR(50) NULL,
INSERT_TIME DATETIME NULL ,
INSERT_OPERATOR VARCHAR(50) NULL ,
INSERT_OPERATOR_ID BIGINT(20) NULL ,
MODIFY_TIME DATETIME NULL ,
MODIFY_OPERATOR VARCHAR(50) NULL ,
MODIFY_OPERATOR_ID BIGINT(20) NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='主机环境节点表';


ALTER TABLE NBO_PROJECT_ENV ADD HOST_MODETYPE VARCHAR(32);

set sql_safe_updates=0;
UPDATE  NBO_PROJECT_ENV a SET a.HOST_MODETYPE='singleMode' WHERE a.ENV_TYPE = 'HOST';
set sql_safe_updates=1;
-- 2017.10.26 end
